/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOERFPDF
#define ROOERFPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooErfPdf : public RooAbsPdf {
public:
  RooErfPdf() {} ; 
  RooErfPdf(const char *name, const char *title,
	      RooAbsReal& _m,
	      RooAbsReal& _par1,
	      RooAbsReal& _par2,
	      RooAbsReal& _par3,
	      RooAbsReal& _par4);
  RooErfPdf(const RooErfPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooErfPdf(*this,newname); }
  inline virtual ~RooErfPdf() { }

protected:

  RooRealProxy m ;
  RooRealProxy par1 ;
  RooRealProxy par2 ;
  RooRealProxy par3 ;
  RooRealProxy par4 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooErfPdf,1) // Your description goes here...
};
 
#endif
