/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooWindowPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooWindowPdf) 

 RooWindowPdf::RooWindowPdf(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _hi,
                        RooAbsReal& _low) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   hi("hi","hi",this,_hi),
   low("low","low",this,_low)
 { 
 } 


 RooWindowPdf::RooWindowPdf(const RooWindowPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   hi("hi",this,other.hi),
   low("low",this,other.low)
 { 
 } 



 Double_t RooWindowPdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return x > low && x< hi ? 1:0.0 ; 
 } 



