/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooApollonios.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

//ClassImp(RooApollonios) 

 RooApollonios::RooApollonios(const char *name, const char *title, 
                        RooAbsReal& _m,
                        RooAbsReal& _m0,
                        RooAbsReal& _sigma,
                        RooAbsReal& _b,
                        RooAbsReal& _a,
                        RooAbsReal& _n) :
   RooAbsPdf(name,title), 
   m("m","m",this,_m),
   m0("m0","m0",this,_m0),
   sigma("sigma","sigma",this,_sigma),
   b("b","b",this,_b),
   a("a","a",this,_a),
   n("n","n",this,_n)
 { 
 } 


 RooApollonios::RooApollonios(const RooApollonios& other, const char* name) :  
   RooAbsPdf(other,name), 
   m("m",this,other.m),
   m0("m0",this,other.m0),
   sigma("sigma",this,other.sigma),
   b("b",this,other.b),
   a("a",this,other.a),
   n("n",this,other.n)
 { 
 } 



 Double_t RooApollonios::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   //return 1.0 ; 
   Double_t xi = (m-m0)/sigma;
   Double_t xi2 = xi*xi;
   if (a < 0) xi = -xi;
   Double_t absa = fabs((Double_t)a);
   Double_t a2 = a*a;
   
   if (xi >= -absa) {
     return exp(-b*sqrt(1+ xi2));
   } else {
     Double_t B =  -1.*(absa - n*sqrt(1+a2)/(b*absa));
     Double_t A = exp(-b*sqrt(1+a2)) *pow(B+absa,n);
     return A*pow(B-xi,-n);
   }
 } 



