/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooBiApollonios.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

//ClassImp(RooBiApollonios) 

RooBiApollonios::RooBiApollonios(const char *name, const char *title, 
                                 RooAbsReal& _m,
                                 RooAbsReal& _m0,
                                 RooAbsReal& _sigma_l,
                                 RooAbsReal& _sigma_r,
                                 RooAbsReal& _b_l,
                                 RooAbsReal& _b_r,
                                 RooAbsReal& _a_l,
                                 RooAbsReal& _a_r,
                                 RooAbsReal& _n_l,
                                 RooAbsReal& _n_r) :
  RooAbsPdf(name,title), 
  m("m","m",this,_m),
  m0("m0","m0",this,_m0),
  sigma_l("sigma_l","sigma_l",this,_sigma_l),
  sigma_r("sigma_r","sigma_r",this,_sigma_r),
  b_l("b_l","b_l",this,_b_l),
  b_r("b_r","b_r",this,_b_r),
  a_l("a_l","a_l",this,_a_l),
  a_r("a_r","a_r",this,_a_r),
  n_l("n_l","n_l",this,_n_l),
  n_r("n_r","n_r",this,_n_r)
{ 
} 


 RooBiApollonios::RooBiApollonios(const RooBiApollonios& other, const char* name) :  
   RooAbsPdf(other,name), 
   m("m",this,other.m),
   m0("m0",this,other.m0),
   sigma_l("sigma_l",this,other.sigma_l),
   sigma_r("sigma_r",this,other.sigma_r),
   b_l("b_l",this,other.b_l),
   b_r("b_r",this,other.b_r),
   a_l("a_l",this,other.a_l),
   a_r("a_r",this,other.a_r),
   n_l("n_l",this,other.n_l),
   n_r("n_r",this,other.n_r)
 { 
 } 



 Double_t RooBiApollonios::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   //return 1.0 ; 
   
   if(m>m0){
     Double_t xi = (m-m0)/sigma_r;
     if (xi <= a_r) {
       return exp(-b_r*sqrt(1+ xi*xi));
     } else {
       Double_t B = -1.*(a_r - n_r*sqrt(1+a_r*a_r)/(b_r*a_r));
       Double_t A = exp(-b_r*sqrt(1+a_r*a_r)) *pow(B+a_r,n_r);
       return A*pow(B+xi,-n_r);
     }
   }else{
     Double_t xi = (m-m0)/sigma_l;
     if (xi >= -a_l) {
       return exp(-b_l*sqrt(1+ xi*xi));
     } else {
       Double_t B = -1.*(a_l - n_l*sqrt(1+a_l*a_l)/(b_l*a_l));
       Double_t A = exp(-b_l*sqrt(1+a_l*a_l)) *pow(B+a_l,n_l);
       return A*pow(B-xi,-n_l);
     }
   }
 } 
