/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOBIAPOLLONIOS
#define ROOBIAPOLLONIOS

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooBiApollonios : public RooAbsPdf {
public:
  RooBiApollonios() {} ; 
  RooBiApollonios(const char *name, const char *title,
                  RooAbsReal& _m,
                  RooAbsReal& _m0,
                  RooAbsReal& _sigma_l,
                  RooAbsReal& _sigma_r,
                  RooAbsReal& _b_l,
                  RooAbsReal& _b_r,
                  RooAbsReal& _a_l,
                  RooAbsReal& _a_r,
                  RooAbsReal& _n_l,
                  RooAbsReal& _n_r);
  RooBiApollonios(const RooBiApollonios& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooBiApollonios(*this,newname); }
  inline virtual ~RooBiApollonios() { }

protected:

  RooRealProxy m ;
  RooRealProxy m0 ;
  RooRealProxy sigma_l ;
  RooRealProxy sigma_r ;
  RooRealProxy b_l ;
  RooRealProxy b_r ;
  RooRealProxy a_l ;
  RooRealProxy a_r ;
  RooRealProxy n_l ;
  RooRealProxy n_r ;
  
  Double_t evaluate() const ;

private:
  
  //ClassDef(RooBiApollonios,1) // Your description goes here...
};
 
#endif
