/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOLOUSONNA
#define ROOLOUSONNA

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooLousonna : public RooAbsPdf {
public:
  RooLousonna() {} ; 
  RooLousonna(const char *name, const char *title,
              RooAbsReal& _m,
              RooAbsReal& _m0,
              RooAbsReal& _sigma,
              RooAbsReal& _nu,
              RooAbsReal& _alpha,
              RooAbsReal& _n);
  RooLousonna(const RooLousonna& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooLousonna(*this,newname); }
  inline virtual ~RooLousonna() { }

protected:

  RooRealProxy m ;
  RooRealProxy m0 ;
  RooRealProxy sigma ;
  RooRealProxy nu ;
  RooRealProxy alpha ;
  RooRealProxy n ;
  
  Double_t evaluate() const ;
  Int_t getAnalyticalIntegral( RooArgSet& allVars,  RooArgSet& analVars, const char* rangeName=0 ) const;
  Double_t analyticalIntegral( Int_t code, const char* rangeName=0 ) const;
  
private:

  //ClassDef(RooLousonna,1) // Your description goes here...
};
 
#endif
