/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOPARTBIAPOLLONIOS
#define ROOPARTBIAPOLLONIOS

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooPartBiApollonios : public RooAbsPdf {
public:
  RooPartBiApollonios() {} ; 
  RooPartBiApollonios(const char *name, const char *title,
                  RooAbsReal& _m,
                  RooAbsReal& _m0,
                  RooAbsReal& _sigma,
                  RooAbsReal& _b,
                  RooAbsReal& _a_l,
                  RooAbsReal& _a_r,
                  RooAbsReal& _n_l,
                  RooAbsReal& _n_r);
  RooPartBiApollonios(const RooPartBiApollonios& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooPartBiApollonios(*this,newname); }
  inline virtual ~RooPartBiApollonios() { }

protected:

  RooRealProxy m ;
  RooRealProxy m0 ;
  RooRealProxy sigma ;
  RooRealProxy b ;
  RooRealProxy a_l ;
  RooRealProxy a_r ;
  RooRealProxy n_l ;
  RooRealProxy n_r ;
  
  Double_t evaluate() const ;

private:
  
  //ClassDef(RooPartBiApollonios,1) // Your description goes here...
};
 
#endif
