/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOSTUDENTT
#define ROOSTUDENTT

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooStudentT : public RooAbsPdf {
public:
  RooStudentT() {} ; 
  RooStudentT(const char *name, const char *title,
              RooAbsReal& _m,
              RooAbsReal& _m0,
              RooAbsReal& _sigma,
              RooAbsReal& _nu);
  RooStudentT(const RooStudentT& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooStudentT(*this,newname); }
  inline virtual ~RooStudentT() { }
  
  virtual Int_t getAnalyticalIntegral( RooArgSet& allVars,  RooArgSet& analVars, const char* rangeName=0 ) const;
  virtual Double_t analyticalIntegral( Int_t code, const char* rangeName=0 ) const;
  
  virtual Int_t getMaxVal(const RooArgSet& vars) const ;
  virtual Double_t maxVal(Int_t code) const ;
  
protected:

  RooRealProxy m ;
  RooRealProxy m0 ;
  RooRealProxy sigma ;
  RooRealProxy nu ;
  
  Double_t evaluate() const ;
  
private:

  //ClassDef(RooStudentT,1) // Your description goes here...
};
 
#endif
